<div class="paper-container">
<div class="about-banner">
        <h1>About Zesty</h1>
</div>

<main class="intro wrapper">
<p class="slogan mar-bot">Crafted with finesse, served with soul.</p>
    <section class="sect-1">
            <h3>Crafted with finesse, served with soul — it's more than a motto. It's our method.</h3>
        <p>
            At Zesty, we believe in the quiet power of intention. From the architecture of our cocktails to the atmosphere of our loft, every detail is designed to elevate the experience. We're not here to overwhelm — we're here to awaken your palate, spark your curiosity, and make space for meaningful moments.
        </p>
        </section>

    <section class="sect-1">
        <h3>Refinement Without Pretension</h3>
        <p>
            Zesty was born from a love of balance — between bold flavors and subtle nuance, between sleek modernism and soulful hospitality. We draw inspiration from global traditions and contemporary technique, using fresh, high-quality ingredients to craft drinks that are both familiar and unexpected.
        </p>
        <p>
            We serve with warmth, precision, and just enough edge to keep things interesting.
        </p>
        </section>

        <section class="sect-1">
            <h3>A Loft Above the Noise</h3>
            <p>
            Nestled above the city, our bar is a curated escape. Industrial textures meet soft lighting, clean lines meet cozy corners — it;s a space designed to breathe. Whether you;re joining us for a slow sip at the bar or an intimate evening with friends, Zesty invites you to settle in and stay awhile.
            </p>
        </section>
    
        <section class="sect-1">
        <h3>The Zesty Team</h3>
        <p>
            We're a collective of bartenders, hosts, and artists who believe in the magic of a well-made drink and a well-timed smile. Every member of our team is trained in both the science and soul of hospitality — and we're always ready to shake up something special.
        </p>
        </section>
    
        <div>
        <p>
            Taste is personal. At Zesty, it's also an experience.
        </p>
        <div class="buttons">
        <a href="?menu" class="btn">Explore the Menu</a>
        <a href="?reservation" class="btn">Reserve a Table</a>
        </div>
        <cite>All text is generated by <a href="https://chatgpt.com/">Chatgpt</a></cite>
        </div>


    </main>