<body>
<div class="paper-container">
<div class="hero">
        <h1>Zesty.<br>
        <span>"Crafted with Finesse, Served with Soul"</span></h1>
</div>

<article class="wrapper">
        <section class="em55">
            <div id="img-1" class="col-50"><img src="./images/ash-edmonds-96EOKC5d200-unsplash.png" alt=""><cite>Photo by <a href="https://unsplash.com/de">unsplash.com</a></cite></div>
            <div class="col-50 sect-text"><h3>Cocktails with Character. A Space with Soul.</h3>
            <p>At Zesty, every cocktail tells a story — of balance, technique, and bold expression.
                We craft with precision, pour with care, and serve in a space designed for connection.
                <br>
                <br>

                Whether you're seeking something new or simply something right, you'll find your flavor here.</p>
            </div>
        </section>

        <section class="row-reverse em55">
            <div id="img-2" class="col-33"><img src="./images/alexander-jawfox-ts2e1Dia5Ec-unsplash.png" alt="Picture of drinks behind the bar"><cite>Photo by <a href="https://pexels.com/de">pexels.com</a></cite></div>
            <div class="col-66 mar-r sect-text">
            <h3>Why Zesty?</h3>
            <p>Because taste is more than flavor — it's feeling.
                Because every detail matters, from the curve of the glass to the calm between tracks.
                Because a cocktail, when crafted with finesse and served with soul, can turn a moment into a memory.
                <br>
                <br>
                
                Zesty is for those who appreciate the in-between — the golden hour glow, the perfect pour, the conversation that lingers.
                <br>
                <br>
                
                Come up. Slow down. Stay awhile.</p>

                <cite>All text is generated by <a href="https://chatgpt.com">Chatgpt</a></cite>   
            </div>
        </section>

</article> 
</div> 
</body>
</html>