<?php
include 'config/db.php';

$stmt = $db->query('SELECT * FROM menu ORDER BY cocktail_category');
$menu_items = $stmt->fetchAll();

$grouped_menu = [];
foreach($menu_items AS $item){
    $grouped_menu[$item['cocktail_category']][] = $item;
}

?>



<div class="paper-container">

<div class="cocktail-banner">
        <h1>Signature Cocktail Menu</h1>        
</div>


<main class="wrapper">

<p class="mar-bot">
    Each cocktail is a composition — artful, intentional, and designed to awaken the senses.
    We blend premium spirits, seasonal ingredients, and modern technique to deliver flavor with finesse.
</p>

<?php foreach($grouped_menu AS $category => $items): ?>
    <section class="cocktail-section">
    
    <h3><?=$category?></h3>
    <?php foreach ($items AS $item): ?>
        <div class="cocktail">
            <h4><?= $item['cocktail_name']?></h4>
            <p class="desc"><?= $item['description']?></p>
            <p class="desc"><?= $item['ingredients']?></p>
        </div>
    <?php endforeach; ?>
    </section>
<?php endforeach; ?>



        <section class="intro">
            <p><strong>Note:</strong> Our menu rotates seasonally. Ask your bartender about new or off-menu creations.  
            All cocktails can be tailored to your taste upon request.</p>
            <cite>All text is generated by <a href="https://chatgpt.com/">Chatgpt</a></cite>
        </section>

    </main>
    </div>